service: optimize-image
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 256
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"


functions:
  optimizer: 
    handler: optimizer.handle
    environment:
      bucket: anselme
    events:
      - s3:
          bucket: anselme
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
      - s3:
          bucket: anselme
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg

